// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {themes} from '../models';

export function GetCurrentTheme():Promise<themes.Theme>;

export function GetFAIcon(arg1:string):Promise<string>;
