// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentTheme() {
  return window['go']['main']['App']['GetCurrentTheme']();
}

export function GetFAIcon(arg1) {
  return window['go']['main']['App']['GetFAIcon'](arg1);
}
